version: 2
build:
  image: latest

sphinx:
  # Ignores it, apprently
  # configuration: docs/source/conf_rtfd.py
  configuration: docs/source/conf.py
  builder: html

formats: [epub]

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
# This is not used to don't depend on python3-gpg that depends on libgpgme-dev
# and it's not installed in rtfd.
#   # To run "pip install ." in rtfd.io
#   pip_install: true

# # To run "pip install .[doc]" in rtfd.io
# extra_requirements:
#   - doc
